In [29]:
import numpy as np

In [31]:

m = 3
n = 5

A = np.random.normal(size=(n,m))

print(A)

set_m = np.eye(m)
set_n = np.matmul(A, set_m)

print(set_n)


[[ 0.5252424   0.1989483   1.37664643]
 [ 0.70155201 -0.4034871  -1.0657902 ]
 [-2.03120117 -0.39198057 -0.86936468]
 [ 0.44195072 -0.04399233 -2.00131359]
 [ 0.30659661  1.00274479 -0.19205468]]
[[ 0.5252424   0.1989483   1.37664643]
 [ 0.70155201 -0.4034871  -1.0657902 ]
 [-2.03120117 -0.39198057 -0.86936468]
 [ 0.44195072 -0.04399233 -2.00131359]
 [ 0.30659661  1.00274479 -0.19205468]]


In [35]:
for i in range(n) :
    for j in range(i+1) :
        print(f"n_{i} . n_{j}  =  {np.dot(set_n[i], set_n[j]):.2f}")

n_0 . n_0  =  2.21
n_1 . n_0  =  -1.18
n_1 . n_1  =  1.79
n_2 . n_0  =  -2.34
n_2 . n_1  =  -0.34
n_2 . n_2  =  5.04
n_3 . n_0  =  -2.53
n_3 . n_1  =  2.46
n_3 . n_2  =  0.86
n_3 . n_3  =  4.20
n_4 . n_0  =  0.10
n_4 . n_1  =  0.02
n_4 . n_2  =  -0.85
n_4 . n_3  =  0.48
n_4 . n_4  =  1.14


In [40]:

M = np.matmul(A.transpose(), A)

l, v = np.linalg.eig(M)
u = np.matmul(A, v)

for i in range(m) :
    for j in range(i+1) :
        print(f"v_{i} . v_{j}  =  {np.dot(v[i], v[j]):.2f}")
        

v_0 . v_0  =  1.00
v_1 . v_0  =  -0.00
v_1 . v_1  =  1.00
v_2 . v_0  =  -0.00
v_2 . v_1  =  -0.00
v_2 . v_2  =  1.00


In [41]:

for i in range(m) :
    for j in range(i+1) :
        print(f"u_{i} . u_{j}  =  {np.dot(u.transpose()[i], u.transpose()[j]):.2f}")
        

u_0 . u_0  =  8.25
u_1 . u_0  =  0.00
u_1 . u_1  =  5.05
u_2 . u_0  =  -0.00
u_2 . u_1  =  0.00
u_2 . u_2  =  1.08
